apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdp-quota-customizer-admission-manager
  labels:
    app: cdp-quota-customizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdp-quota-customizer
  template:
    metadata:
      labels:
        app: cdp-quota-customizer
    spec:
      serviceAccount: cdp-quota-customizer-admission-manager-sa
      containers:
        - name: cdp-quota-customizer
          image: daocloud.io/daocloud/cdp-quota-customizer:latest
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/tls.crt
            - -tlsKeyFile=/etc/webhook/certs/tls.key
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: cdp-quota-customizer-admission-manager-certs
      ## By DaoCloud
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      ##
