apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-webhook-cdp-quota-customizer-cfg
  annotations:
    cert-manager.io/inject-ca-from: cdp-customizer/cdp-quota-customizer-webhook-cert
  labels:
    app: cdp-quota-customizer
webhooks:
  - name: validate-cdp-quota-customizer-console.datacreating.com
    clientConfig:
      service:
        name: cdp-quota-customizer-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: monitoring-platform-access
          operator: Exists
    timeoutSeconds: 5
  - name: validate-cdp-quota-customizer-cml.datacreating.com
    clientConfig:
      service:
        name: cdp-quota-customizer-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: associatedCRP
          operator: Exists
    timeoutSeconds: 5
  - name: validate-cdp-quota-customizer-implala.datacreating.com
    clientConfig:
      service:
        name: cdp-quota-customizer-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: istio-injection
          operator: Exists
    timeoutSeconds: 5
  - name: validate-cdp-quota-customizer-monitoring.datacreating.com
    clientConfig:
      service:
        name: cdp-quota-customizer-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: cdp.cloudera/version
          operator: Exists
    timeoutSeconds: 5
  - name: validate-quota-limitrange-ds-parent-namespace.datacreating.com
    clientConfig:
      service:
        name: cdp-quota-customizer-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: ds-parent-namespace
          operator: Exists
    timeoutSeconds: 5